### ISSUE TITLE
install.sh - can't find packages libqt4-dev and libqt4-sql-mysql

### ISSUE THREAD

**Issue by trackerfox** [edgeradio993fm/scripts#1]
Trying to install Rivendell on Raspberry Pi 3 with Raspberry Pi OS 32-bit by this script:
https://raw.githubusercontent.com/edgeradio993fm/scripts/master/install.sh
but it can't find packages libqt4-dev and libqt4-sql-mysql so it fails.

Here is output:
Installing Rivendell dependencies...

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libqt4-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libqt4-sql-mysql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libqt4-dev' has no installation candidate
E: Package 'libqt4-sql-mysql' has no installation candidate

…..cutted, all is ok……

Downloading Rivendell...

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rivendell : Depends: libqt4-dev but it is not installable
             Depends: libqt4-sql-mysql but it is not installable
E: Unable to correct problems, you have held broken packages.

Downloading default configuration...

--2021-11-27 19:01:39--  https://raw.githubusercontent.com/edgeradio993fm/rivendell/master/conf/rd.conf-sample
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5444 (5.3K) [text/plain]
Saving to: ‘/etc/rd.conf’

/etc/rd.conf                                                    100%[=====================================================================================================================================================>]   5.32K  --.-KB/s    in 0.004s

2021-11-27 19:01:39 (1.21 MB/s) - ‘/etc/rd.conf’ saved [5444/5444]

ERROR: Conf rd-bin does not exist!

Creating database and populating database tables...

sudo: rddbmgr: command not found
Failed to start rivendell.service: Unit rivendell.service not found.
Failed to enable unit: Unit file rivendell.service does not exist.
sudo: rdalsaconfig: command not found

You may need to reboot to complete the install.
All done. Enjoy.

**Comment by alastairtech** [comment]
Ah. This is a direct result of the recent transition to Debian 11 Bullseye becoming the base for the latest Raspberry Pi OS. The QT4 packages are no longer supported in the latest release. You can grab a supported Debian 10 Buster Raspberry Pi OS image using the link below. I'll update the install instructions soon...

https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2021-05-28/2021-05-07-raspios-buster-armhf.zip

We will be transitioning to Debian 11 Bullseye with the upcoming release of Rivendell 4. Details and a test install can be found using the link below.

https://github.com/edgeradio993fm/rivendell/wiki/Updates

Let me know how you get on.

**Comment by trackerfox** [comment]
Yes! It works with Debian 10 image. Thank you very much.
